steps:
- name: node:14
  entrypoint: yarn
  args: ['install']
- name: node:14
  entrypoint: yarn
  args: ['build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy']
